---
creation_rules:
    - path_regex: machines/[^/]+/secrets.sops.yaml
      age: age14pf9amc4gslxfy948z8wr2kfjsfskguufdngzqu20cv95j4vg3fq5xkhst
    - path_regex: profiles/personal/[^/]+\.sops\.(?:nix|yaml)
      age: age1p4lpkpggfkarn8ursr79t2jeuppdjnmrkkne7yq8rhr8edkrfs9qrc7e3a
